const computadoras = [
    {
    tipo: 'PC de escritorio',
    marca: 'HP',
    modelo: 'Pavilion',
    ram: 8,
    almacenamiento: '1TB HDD',
    },
    {
    tipo: 'Laptop',
    marca: 'Dell',
    modelo: 'Inspiron',
    ram: 16,
    almacenamiento: '512GB SSD',
    },
    {
    tipo: 'Tableta',
    marca: 'Apple',
    modelo: 'iPad Pro',
    ram: 6,
    almacenamiento: '256GB',
    },
    {
    tipo: 'Servidor',
    marca: 'Lenovo',
    modelo: 'ThinkServer',
    ram: 32,
    almacenamiento: '4TB HDD',
    },
    {
    tipo: 'Computadora portátil 2 en 1',
    marca: 'Asus',
    modelo: 'ZenBook Flip',
    ram: 12,
    almacenamiento: '512GB SSD',
    },
    {
    tipo: 'MacBook',
    marca: 'Apple',
    modelo: 'MacBook Air',
    ram: 16,
    almacenamiento: '1TB SSD',
    },
    {
    tipo: 'Chromebook',
    marca: 'Samsung',
    modelo: 'Chromebook Plus',
    ram: 4,
    almacenamiento: '64GB eMMC',
    },
    {
    tipo: 'Minicomputadora',
    marca: 'Intel',
    modelo: 'NUC',
    ram: 8,
    almacenamiento: '256GB SSD',
    },
    {
    tipo: 'Supercomputadora',
    marca: 'IBM',
    modelo: 'Watson',
    ram: 512,
    almacenamiento: '10PB',
    },
    {
    tipo: 'Computadora de juegos',
    marca: 'MSI',
    modelo: 'Gaming Pro',
    ram: 32,
    almacenamiento: '1TB SSD',
    }];